name:  MARP A HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Instalar MARP CLI
        run: npm install -g @marp-team/marp-cli

      - name: Generar HTML
        run: marp hojadevida.md --html --output index.html

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
